"""api/app.py — FastAPI skeleton (Phase 2). Generated by NB00."""
from fastapi import FastAPI
from pathlib import Path
import pandas as pd, json

app = FastAPI(
    title="FII Intelligence API",
    description="Investor Intelligence Platform — FIIs Brasil",
    version="1.0.0",
)

GOLD = Path(__file__).parent.parent / "data" / "gold"

@app.get("/health")
def health():
    return {"status": "ok", "version": "1.0.0"}

@app.get("/articles")
def articles(limit: int = 20):
    p = GOLD / "dashboard" / "dashboard_articles.parquet"
    if not p.exists():
        return {"error": "Run NB07 first"}
    df = pd.read_parquet(p).head(limit)
    return df.to_dict(orient="records")

@app.get("/sources")
def sources():
    p = GOLD / "dashboard" / "dashboard_sources.parquet"
    if not p.exists():
        return {"error": "Run NB07 first"}
    df = pd.read_parquet(p)
    return df.to_dict(orient="records")
