"""dashboard/chatbot/groq_client.py — Groq chatbot stub. Generated by NB00."""
import os
from groq import Groq

DISCLAIMER = (
    "Esta análise é gerada por IA com base em dados públicos. "
    "Não constitui recomendação de investimento. "
    "Consulte um assessor financeiro certificado antes de tomar decisões."
)

def get_groq_client(custom_api_key: str = None) -> Groq:
    api_key = custom_api_key or os.getenv("GROQ_API_KEY", "")
    if not api_key:
        raise ValueError("GROQ_API_KEY não definido no ambiente e nenhum custom key fornecido.")
    return Groq(api_key=api_key)

def chat(user_message: str, context: str = "", custom_api_key: str = None) -> str:
    client = get_groq_client(custom_api_key)
    system_prompt = (
        "Você é um assistente especializado em fundos imobiliários brasileiros (FIIs). "
        "Responda sempre em português. "
        f"Contexto de mercado: {context[:2000] if context else 'Não disponível.'}\n\n"
        f"AVISO LEGAL: {DISCLAIMER}"
    )
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_message},
        ],
        max_tokens=800,
        temperature=0.3,
    )
    return response.choices[0].message.content + f"\n\n---\n⚠️ {DISCLAIMER}"

